name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build backend
        working-directory: backend
        run: |
          npm ci
          # npm test   # <-- uncomment if you have tests

      - name: Build frontend
        working-directory: frontend
        run: |
          # use legacy-peer-deps to bypass react-flow-renderer<>react mismatch
          npm install --legacy-peer-deps
          npm run build

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            cd /opt/topology-dashboard
            git pull origin main
            npm ci
            npm run build --prefix frontend
            systemctl restart topology-dashboard
